server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: com.jessica.springcloud.pojo
  mapper-locations: classpath:com/jessica/springcloud/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# spring
spring:
  application:
    name: springcloud-provider-group
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
